import { z } from 'zod'

// ✅ CORRECTED - Aligned with Backend

// Machine Preset schema
export const machinePresetSchema = z.object({
  name: z.string().max(100, 'Nome deve ter no máximo 100 caracteres').optional(), // auto-generated by the API when empty
  description: z.string().max(500).optional(),
  is_default: z.boolean().optional(),
  brand: z.string().max(100).optional(),
  model: z.string().max(100).optional(),
  build_volume_x: z.number().positive('Volume X deve ser maior que zero'),
  build_volume_y: z.number().positive('Volume Y deve ser maior que zero'),
  build_volume_z: z.number().positive('Volume Z deve ser maior que zero'),
  nozzle_diameter: z.number().positive('Diâmetro do bico deve ser maior que zero'),
  layer_height_min: z.number().positive('Altura mínima de camada deve ser maior que zero'),
  layer_height_max: z.number().positive('Altura máxima de camada deve ser maior que zero'),
  print_speed_max: z.number().positive('Velocidade máxima deve ser maior que zero'),
  power_consumption: z.number().positive('Consumo de energia deve ser maior que zero'),
  bed_temperature_max: z.number().positive('Temperatura máxima da mesa deve ser maior que zero'),
  extruder_temperature_max: z.number().positive('Temperatura máxima do extrusor deve ser maior que zero'),
  filament_diameter: z.number().positive('Diâmetro do filamento deve ser maior que zero'),
  cost_per_hour: z.number().min(0, 'Custo por hora deve ser 0 ou maior'),
})

export type MachinePresetFormData = z.infer<typeof machinePresetSchema>

// Energy Preset schema
export const energyPresetSchema = z.object({
  name: z.string().max(100, 'Nome deve ter no máximo 100 caracteres').optional(), // auto-generated by the API when empty
  description: z.string().max(500).optional(),
  is_default: z.boolean().optional(),
  country: z.string().max(100).optional(),
  state: z.string().max(100).optional(),
  city: z.string().max(100).optional(),
  energy_cost_per_kwh: z.number().positive('Custo por kWh deve ser maior que zero'),
  currency: z.string().length(3, 'Moeda deve ter 3 caracteres (ex: BRL, USD)'),
  provider: z.string().max(100).optional(),
  tariff_type: z.string().max(100).optional(),
  peak_hour_multiplier: z.number().positive('Multiplicador de pico deve ser maior que zero').optional(),
  off_peak_hour_multiplier: z
    .number()
    .positive('Multiplicador fora de pico deve ser maior que zero')
    .optional(),
})

export type EnergyPresetFormData = z.infer<typeof energyPresetSchema>

// Cost Preset schema
export const costPresetSchema = z.object({
  name: z.string().max(100, 'Nome deve ter no máximo 100 caracteres').optional(), // auto-generated by the API when empty
  description: z.string().max(500).optional(),
  is_default: z.boolean().optional(),
  labor_cost_per_hour: z.number().min(0, 'Custo de mão de obra deve ser 0 ou maior'),
  packaging_cost_per_item: z.number().min(0, 'Custo de embalagem deve ser 0 ou maior'),
  shipping_cost_base: z.number().min(0, 'Custo base de envio deve ser 0 ou maior'),
  shipping_cost_per_gram: z.number().min(0, 'Custo de envio por grama deve ser 0 ou maior'),
  overhead_percentage: z.number().min(0, 'Overhead deve ser 0 ou maior').max(100, 'Overhead deve ser no máximo 100'),
  profit_margin_percentage: z
    .number()
    .min(0, 'Margem de lucro deve ser 0 ou maior')
    .max(1000, 'Margem de lucro deve ser no máximo 1000%'),
  post_processing_cost_per_hour: z.number().min(0, 'Custo de pós-processamento deve ser 0 ou maior'),
  support_removal_cost_per_hour: z.number().min(0, 'Custo de remoção de suporte deve ser 0 ou maior'),
  quality_control_cost_per_item: z.number().min(0, 'Custo de controle de qualidade deve ser 0 ou maior'),
  failure_rate_percentage: z
    .number()
    .min(0, 'Taxa de falha deve ser 0 ou maior')
    .max(100, 'Taxa de falha deve ser no máximo 100%'),
  waste_grams_per_color_change: z.number().min(0, 'Desperdício por troca de cor deve ser 0 ou maior'),
})

export type CostPresetFormData = z.infer<typeof costPresetSchema>


/** Maps an empty `<input type="number">` to `undefined` instead of NaN (for optional fields). */
export function optionalNumber(value: unknown): number | undefined {
  if (value === '' || value === null || value === undefined) return undefined
  const parsed = typeof value === 'number' ? value : Number(value)
  return Number.isFinite(parsed) ? parsed : undefined
}

/** Trims the optional name; returns undefined when blank so the API auto-generates it. */
export function normalizeOptionalName(name: string | undefined): string | undefined {
  const trimmed = name?.trim()
  return trimmed ? trimmed : undefined
}

// Print profile schema
export const profileSchema = z.object({
  name: z.string().max(100, 'Nome deve ter no máximo 100 caracteres').optional(),
  description: z.string().max(500, 'Descrição deve ter no máximo 500 caracteres').optional(),
  machine_preset_id: z
    .string({ required_error: 'Selecione um preset de máquina' })
    .uuid('Selecione um preset de máquina'),
  energy_preset_id: z
    .string({ required_error: 'Selecione um preset de energia' })
    .uuid('Selecione um preset de energia'),
  cost_preset_id: z.string().uuid().optional(),
  is_default: z.boolean().optional(),
})

export type ProfileFormData = z.infer<typeof profileSchema>
